//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosFijo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ActivosFijosEntities : DbContext
    {
        public ActivosFijosEntities()
            : base("name=ActivosFijosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Municipio> Municipios { get; set; }
        public virtual DbSet<Plane> Planes { get; set; }
        public virtual DbSet<Provincia> Provincias { get; set; }
        public virtual DbSet<TblActivo> TblActivoes { get; set; }
        public virtual DbSet<TblCategoria> TblCategorias { get; set; }
        public virtual DbSet<TblLocacione> TblLocaciones { get; set; }
        public virtual DbSet<TblMovimiento> TblMovimientos { get; set; }
        public virtual DbSet<TblOrigene> TblOrigenes { get; set; }
        public virtual DbSet<TblPersona> TblPersonas { get; set; }
        public virtual DbSet<TblTipoBaja> TblTipoBajas { get; set; }
        public virtual DbSet<TblTiposActivo> TblTiposActivos { get; set; }
        public virtual DbSet<TblUsuario> TblUsuarios { get; set; }
    }
}
