//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosFijo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblActivo
    {
        public int Id { get; set; }
        public string cDescripcion { get; set; }
        public string cDetalle { get; set; }
        public Nullable<int> IdOrigen { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public Nullable<int> IdLocacion { get; set; }
        public Nullable<int> IdTipoActivo { get; set; }
        public Nullable<double> nValor { get; set; }
        public Nullable<double> nDepreciacion { get; set; }
        public Nullable<double> nValorLibro { get; set; }
        public Nullable<int> cEstatus { get; set; }
        public Nullable<System.DateTime> dFechaActivo { get; set; }
        public string cCuentaContable { get; set; }
        public string cAsignacion { get; set; }
        public Nullable<System.DateTime> dfechaRegistro { get; set; }
        public string cUsuario { get; set; }
        public string cMarca { get; set; }
        public string cModelo { get; set; }
        public string cNoSerial { get; set; }
        public string codigoOrigen { get; set; }
        public string codigoBN { get; set; }
        public string CodigoMINPRE { get; set; }
        public string CodigoMINERD { get; set; }
        public Nullable<int> CodigoDIGEPEP { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public string ActualizadoPor { get; set; }
        public Nullable<int> IdPersona { get; set; }
    
        public virtual TblCategoria TblCategoria { get; set; }
        public virtual TblLocacione TblLocacione { get; set; }
        public virtual TblOrigene TblOrigene { get; set; }
        public virtual TblTiposActivo TblTiposActivo { get; set; }
        public virtual TblPersona TblPersona { get; set; }
    }
}
