//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosFijo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPersona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblPersona()
        {
            this.TblActivoes = new HashSet<TblActivo>();
            this.TblMovimientos = new HashSet<TblMovimiento>();
        }
    
        public int Id { get; set; }
        public string cDocumento { get; set; }
        public string cNombre { get; set; }
        public string cApellido { get; set; }
        public string cSexo { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Correo { get; set; }
        public Nullable<int> IdPlan { get; set; }
        public string RegistradoPor { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> provinciaid { get; set; }
        public string provincia { get; set; }
        public Nullable<int> municipioid { get; set; }
        public string municipio { get; set; }
        public string telefono { get; set; }
        public string Cargo { get; set; }
    
        public virtual Municipio Municipio1 { get; set; }
        public virtual Plane Plane { get; set; }
        public virtual Provincia Provincia1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblActivo> TblActivoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMovimiento> TblMovimientos { get; set; }
    }
}
