//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosFijo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUsuario
    {
        public int Id { get; set; }
        public string cUsuario { get; set; }
        public string cClave { get; set; }
        public string cNombre { get; set; }
        public string rol { get; set; }
    }
}
